# There are no constraints in this XDC file, because
#
# (a) the only clock in the system is generated by the processor part, and
#     it's already constrained through generated XDCs, and
# (b) there are no pin placements, since the board has nothing connected to
#     the PL pins, except for general-purpose expansion connectors.

